swiftmailer:
  transport:  "smtp"
  host:      "%env(MAILGUN_SMTP_SERVER)%"
  username:  "%env(MAILGUN_SMTP_LOGIN)%"
  password:  "%env(MAILGUN_SMTP_PASSWORD)%"
  port:      "%env(int:MAILGUN_SMTP_PORT)%"
  encryption: tls
