controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
api_login_check:
    path: /api/login_check
app_get_image:
    path: /api/images/{filename}
    controller: App\Controller\ImageController::getImage
    methods: GET